repos:
  - repo: local
    hooks:
    - id: run-clippy
      name: Running cargo clippy fix. Please wait .
      entry: cargo clippy --fix --allow-staged
      language: system
      pass_filenames: false