repos:
  - repo: local
    hooks:
    - id: run-clippy
      # language: script
      name: run clippy
      description: Running cargo clippy fix
      entry: cargo clippy --fix --allow-staged
      language: system
      pass_filenames: false